CREATE TABLE `read_record` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `title` varchar(255) NOT NULL COMMENT '书名或文章标题',
  `type` tinyint(4) NOT NULL COMMENT '类型：1-书籍，2-文章/网页',
  `author` varchar(100) DEFAULT NULL COMMENT '作者',
  `url` varchar(500) DEFAULT NULL COMMENT '链接（主要针对文章/网页或豆瓣链接）',
  `cover_img` varchar(500) DEFAULT NULL COMMENT '封面图片链接',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态：0-未开始，1-阅读中，2-已读完，3-搁置',
  `total_progress` int(11) DEFAULT '0' COMMENT '总进度（总页数或100表示百分比）',
  `current_progress` int(11) DEFAULT '0' COMMENT '当前进度（当前页数或当前百分比）',
  `start_time` datetime DEFAULT NULL COMMENT '开始阅读时间',
  `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
  `remark` varchar(1000) DEFAULT NULL COMMENT '备注/读后感',
  `user_id` bigint(20) NOT NULL COMMENT '归属用户ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_user` bigint(20) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(4) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='阅读记录表';
